version: "3.8"
services:
  db:
    image: postgres:15
    container_name: arkidb
    restart: always
    environment:
      POSTGRES_PASSWORD: test1234
      POSTGRES_USER: admin
      POSTGRES_DB: arkidb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
